STOP_WORDS_FR = ['0', '1', '2', '3', 'a', 'ah', 'ai', 'aime', 'aller', 'alors', 'ans', 'apres', 'après', 'as', 'au',
    'aussi', 'autre', 'autres', 'aux', 'avais', 'avait', 'avant', 'avec', 'avez', 'avoir', 'b', 'bah', 'bcp',
    'beaucoup', 'bien', 'bon', 'bonjour', 'bonne', 'bref', 'c', "c'est", "c'était", 'ca', 'ce', 'cela',
    'celle', 'celui', 'ces', 'cest', 'cet', 'cetait', 'cette', 'ceux', 'chaque', 'chez', 'co', 'comme',
    'comment', 'compte', 'contre', 'coup', 'cours', 'crois', 'cétait', 'c’est', 'd', 'dans', 'de', 'deja',
    'depuis', 'des', 'detre', 'deux', 'dire', 'dis', 'dit', 'dm', 'dois', 'doit', 'donc', 'du', 'déjà',
    'dêtre', 'e', 'eh', 'elle', 'elles', 'en', 'encore', 'entre', 'envie', 'es', 'est', 'estce', 'et', 'etais', 'etait',
    'etc', 'ete', 'etes', 'etre', 'eu', 'f', 'faire', 'fais', 'fait', 'faites', 'faut', 'fois', 'font', 'g',
    'genre', 'gens', 'grave', 'gros', 'gt', 'h', 'hein', 'https', 'i', 'il', 'ils', 'j', "j'ai", "j'aime",
    "j'avais", "j'me", "j'suis", "j'vais", 'jai', 'jaime', 'jamais', 'javais', 'je', 'jen', 'jme', 'jour',
    'journee', 'journée', 'jsp', 'jsuis', 'jte', 'juste', 'jvais', 'jveux', 'jetais', 'jétais', 'j’ai', 'k', 'l', 'la',
    'le', 'les', 'leur', 'leurs', 'lol', 'lui', 'là', 'm', 'ma', 'maintenant', 'mais', 'mal', 'mdr', 'mdrr',
    'mdrrr', 'mdrrrr', 'me', 'mec', 'meme', 'merci', 'merde', 'mes', 'met', 'mettre', 'mieux', 'mis', 'mm',
    'moi', 'moins', 'moment', 'mon', 'monde', 'mtn', 'même', 'n', 'na', 'nan', 'ne', 'nest', 'ni', 'nn',
    'non', 'nos', 'notre', 'nous', 'o', 'of', 'oh', 'ok', 'on', 'ont', 'ou', 'ouais', 'oui', 'où', 'p', 'par',
    'parce', 'parle', 'pas', 'passe', 'pcq', 'pense', 'personne', 'peu', 'peut', 'peutetre', 'peutêtre', 'peux',
    'plus', 'pour', 'pourquoi', 'pq', 'pr', 'prend', 'prendre', 'prends', 'pris', 'ptdr', 'ptdrrr', 'ptn',
    'pu', 'putain', 'q', 'qd', 'qu', "qu'il", "qu'on", 'quand', 'que', 'quel', 'quelle', 'quelque', 'quelques',
    'quelquun', 'qui', 'quil', 'quils', 'quoi', 'quon', 'r', 'rien', 'rt', 's', 'sa', 'sais', 'sait', 'sans',
    'se', 'sera', 'ses', 'sest', 'si', 'sil', 'soir', 'soit', 'son', 'sont', 'suis', 'super', 'sur', 't',
    'ta', 'tas', 'te', 'tellement', 'temps', 'tes', 'tete', 'the', 'tjrs', 'tjs', 'toi', 'ton', 'toujours',
    'tous', 'tout', 'toute', 'toutes', 'tres', 'trop', 'trouve', 'trouvé', 'très', 'tt', 'tu', 'tête', 'u',
    'un', 'une', 'v', 'va', 'vais', 'vas', 'veut', 'veux', 'via', 'vie', 'viens', 'voila', 'voilà', 'voir',
    'vois', 'voit', 'vont', 'vos', 'votre', 'vous', 'vrai', 'vraiment', 'vs', 'vu', 'w', 'wsh', 'x', 'xd',
    'y', 'ya', 'z', 'à', 'ça', 'ça', 'étais', 'était', 'été', 'êtes', 'être', '–—', '-', '']

STOP_WORDS_EN = ['ve', 'way', 'here', 'some', 'watch', 'far', '10', 'there', 'too', '2012', 'show', 'say',
    'who', 'away','live', 'morning', 'if', 'real', 'still', 'off', 'hard', 'sleep', 'work', 'time', 'lmao', 'being',
    'old', 'cause', 'wish', 'had', 'about', 'school', 'find', 'check', 'wanna', 'should', 'smh', 'free', 'could',
    'fucking', 'with', 'or', 'never', 'its', 'bed', 'tonight', 'into', 'and', 'head', 'please', 'up', 'that',
    'it', 'them', 'an', 'hop', 'world', 'lt', 'another', 'bout', 'what', 'my', 'out', 'ever', 'nice', 'home',
    'hope', 'again', 'from', 'would', 'today', 'next', 'were', 'other', 'girl', 'done', 'down', 'most', 'class',
    'tomorrow', 'care', 'ross', 'back', 'love', 'these', 'in', 'music', 'doing', 'day', 'look', 'gotta', 'tho',
    'him', 'want', 'where', 'because', 'your', 'was', 'big', 'face', 'by', 'talk', 'amp', 'll', 'hair',
    'ready', 'get', 'over', 'already', 'have', 'guys', 'start', 'when', 'did', 'heart', 'are', 'song',
    'this', 'come', 'right', 'all', 'make', 'their', 'help', 'girls', 'baby', 'looking', 'even', 'now',
    'wait', 'has', 'everyone', 'her', 'week', 'gonna', 'stop', 'how', 'house', 'everything', 'nigga',
    'game', 'hate', 'hip', 'though', 'give', 'people', 'man', 'going', 'let', 'something', 'think', 'two',
    'life', 'twitter', 'someone', 'just', 'bad', 'one', 'does', 'after', 'see', 'for', 'keep', 'news', 'god',
    'like', 'then', 'watching', 'thing', 'play', 'she', 'night', 'niggas', 'best', 're', 'new', 'thanks',
    'dont', 'know', 'mean', 'around', 'tell', 'is', 'not', 'why', 'little', 'well', 'more', 'so', 'us',
    'cool', 'always', 'having', 'shit', 'much', 'need', 'put', 'before', 'ass', 'fuck', 'win', 'good', 'follow',
    'feel', 'can', 'take', 'every', 'im', 'gone', 'cant', 'got', 'call', 'money', 'said', 'video', 'ain',
    'miss', 'tweet', 'getting', 'will', 'thank', 'our', 'year', 'surveys', 'do', 'team', 'than', 'be', 'you',
    'first', 'nothing', 'person', 'photo', 'his', 'at', 'only', 'same', 'we', 'damn', 'go', 'they', 'don',
    'but', 'been', 'days', 'phone', 'better', 'made', 'bitch', 'any', 'many', 'last', 'to', 'no', 'awards',
    'am', 'didn', 'friends', 'great', 'long', 'won', 'he', 'really', 'things']
