STOP_WORDS_FR = ['0', '1', '2', '3', 'a', 'ah', 'ai', 'aime', 'aller', 'alors', 'ans', 'apres', 'après', 'as', 'au',
    'aussi', 'autre', 'autres', 'aux', 'avais', 'avait', 'avant', 'avec', 'avez', 'avoir', 'b', 'bah', 'bcp',
    'beaucoup', 'bien', 'bon', 'bonjour', 'bonne', 'bref', 'c', "c'est", "c'était", 'ca', 'ce', 'cela',
    'celle', 'celui', 'ces', 'cest', 'cet', 'cetait', 'cette', 'ceux', 'chaque', 'chez', 'co', 'comme',
    'comment', 'compte', 'contre', 'coup', 'cours', 'crois', 'cétait', 'c’est', 'd', 'dans', 'de', 'deja',
    'depuis', 'des', 'detre', 'deux', 'dire', 'dis', 'dit', 'dm', 'dois', 'doit', 'donc', 'du', 'déjà',
    'dêtre', 'e', 'eh', 'elle', 'elles', 'en', 'encore', 'entre', 'envie', 'es', 'est', 'estce', 'et', 'etais', 'etait',
    'etc', 'ete', 'etes', 'etre', 'eu', 'f', 'faire', 'fais', 'fait', 'faites', 'faut', 'fois', 'font', 'g',
    'genre', 'gens', 'grave', 'gros', 'gt', 'h', 'hein', 'https', 'i', 'il', 'ils', 'j', "j'ai", "j'aime",
    "j'avais", "j'me", "j'suis", "j'vais", 'jai', 'jaime', 'jamais', 'javais', 'je', 'jen', 'jme', 'jour',
    'journee', 'journée', 'jsp', 'jsuis', 'jte', 'juste', 'jvais', 'jveux', 'jetais', 'jétais', 'j’ai', 'k', 'l', 'la',
    'le', 'les', 'leur', 'leurs', 'lol', 'lui', 'là', 'm', 'ma', 'maintenant', 'mais', 'mal', 'mdr', 'mdrr',
    'mdrrr', 'mdrrrr', 'me', 'mec', 'meme', 'merci', 'merde', 'mes', 'met', 'mettre', 'mieux', 'mis', 'mm',
    'moi', 'moins', 'moment', 'mon', 'monde', 'mtn', 'même', 'n', 'na', 'nan', 'ne', 'nest', 'ni', 'nn',
    'non', 'nos', 'notre', 'nous', 'o', 'of', 'oh', 'ok', 'on', 'ont', 'ou', 'ouais', 'oui', 'où', 'p', 'par',
    'parce', 'parle', 'pas', 'passe', 'pcq', 'pense', 'personne', 'peu', 'peut', 'peutetre', 'peutêtre', 'peux',
    'plus', 'pour', 'pourquoi', 'pq', 'pr', 'prend', 'prendre', 'prends', 'pris', 'ptdr', 'ptdrrr', 'ptn',
    'pu', 'putain', 'q', 'qd', 'qu', "qu'il", "qu'on", 'quand', 'que', 'quel', 'quelle', 'quelque', 'quelques',
    'quelquun', 'qui', 'quil', 'quils', 'quoi', 'quon', 'r', 'rien', 'rt', 's', 'sa', 'sais', 'sait', 'sans',
    'se', 'sera', 'ses', 'sest', 'si', 'sil', 'soir', 'soit', 'son', 'sont', 'suis', 'super', 'sur', 't',
    'ta', 'tas', 'te', 'tellement', 'temps', 'tes', 'tete', 'the', 'tjrs', 'tjs', 'toi', 'ton', 'toujours',
    'tous', 'tout', 'toute', 'toutes', 'tres', 'trop', 'trouve', 'trouvé', 'très', 'tt', 'tu', 'tête', 'u',
    'un', 'une', 'v', 'va', 'vais', 'vas', 'veut', 'veux', 'via', 'vie', 'viens', 'voila', 'voilà', 'voir',
    'vois', 'voit', 'vont', 'vos', 'votre', 'vous', 'vrai', 'vraiment', 'vs', 'vu', 'w', 'wsh', 'x', 'xd',
    'y', 'ya', 'z', 'à', 'ça', 'ça', 'étais', 'était', 'été', 'êtes', 'être', '–—', '-', '']

STOP_WORDS_EN = ['0', '1', '2', '3', '2012', 'a', 'about', 'after', 'again', 'ain', 'all', 'already', 'always', 'am',
                 'amp', 'an', 'and', 'another', 'any', 'are', 'around', 'ass', 'at', 'away', 'b', 'back', 'bad', 'be',
                 'because', 'been', 'before', 'being', 'best', 'better', 'big', 'bitch', 'bout', 'but', 'by', 'c',
                 'can', 'cant', 'care', 'cause', 'check', 'class', 'come', 'cool', 'could', 'd', 'damn', 'day', 'days',
                 'did', 'didn', 'do', 'does', 'doing', 'don', 'done', 'dont', 'down', 'e', 'even', 'ever', 'every',
                 'everyone', 'everything', 'f', 'face', 'far', 'feel', 'find', 'follow', 'for', 'free', 'friends',
                 'from', 'fuck', 'fucking', 'g', 'game', 'get', 'getting', 'girl', 'girls', 'give', 'go', 'god',
                 'going', 'gone', 'gonna', 'good', 'got', 'gotta', 'great', 'guys', 'h', 'had', 'hair', 'hard', 'has',
                 'hate', 'have', 'having', 'he', 'head', 'heart', 'help', 'her', 'here', 'him', 'hip', 'his', 'home',
                 'hop', 'hope', 'house', 'how', 'i', 'if', 'im', 'in', 'into', 'is', 'it', 'its', 'j', 'just', 'k',
                 'keep', 'know', 'l', 'last', 'let', 'life', 'like', 'little', 'live', 'll', 'lmao', 'long', 'look',
                 'looking', 'love', 'lt', 'm', 'made', 'make', 'man', 'many', 'mean', 'miss', 'money', 'more',
                 'morning', 'most', 'much', 'my', 'n', 'need', 'never', 'new', 'news', 'next', 'nice', 'nigga',
                 'niggas', 'night', 'no', 'not', 'nothing', 'now', 'o', 'off', 'old', 'one', 'only', 'or', 'other',
                 'our', 'out', 'over', 'p', 'people', 'person', 'phone', 'photo', 'play', 'please', 'put', 'r', 're',
                 'ready', 'real', 'really', 'right', 'ross', 's', 'said', 'same', 'say', 'school', 'see', 'she', 'shit',
                 'should', 'show', 'sleep', 'smh', 'so', 'some', 'someone', 'something', 'song', 'start', 'still',
                 'stop', 't', 'take', 'talk', 'team', 'tell', 'than', 'thank', 'thanks', 'that', 'the', 'their', 'them',
                 'then', 'there', 'these', 'they', 'thing', 'things', 'think', 'this', 'tho', 'though', 'time', 'to',
                 'today', 'tomorrow', 'tonight', 'too', 'tweet', 'twitter', 'two', 'u', 'up', 'us', 've', 'video', 'w',
                 'wait', 'wanna', 'want', 'was', 'watch', 'watching', 'way', 'we', 'week', 'well', 'were', 'what',
                 'when', 'where', 'who', 'why', 'will', 'win', 'wish', 'with', 'won', 'work', 'world', 'would', 'year',
                 'you', 'your']
